### ISSUE TITLE
stack-allocated buffer (size specified during runtime, and then fixed)

### ISSUE THREAD

**Issue by user706** [user1095108/ca#5]
Currently ca is unusable with stack-allocated buffers (where size is not know at compile time).

Example:
```cpp
  size_t num_el = 3;
  //std::cout << "Enter number of elements: ";                                                                                                                                                              
  //std::cin >> num_el;                                                                                                                                                                                     
  int arr[num_el+1]{};  // alloca is available under gcc etc.
  ca::array<int, num_el, ca::USER>ca(arr);
```

The problem is the 2nd template argument. For a user-defined buffer, this should not be a compile-time template argument, in my opinion; ... in order to allow what I want to do above.

(Another problem. I'm currently on a project that does not (yet) have C++20. )

**Comment by user1095108** [comment]
It must be a bug, I'll take a look :) As regards the c++ version, I wrote an easy implementation + chose a free license so it would be easy to change/tailor the container to your needs.

**Comment by user1095108** [comment]
I wrote this:
```c++
#include "array.hpp"

int main()
{
  constexpr size_t num_el = 3;
  int arr[10];
  ca::array<int, num_el, ca::USER>ca(arr);

  return 0;
}
```

and it compiled fine, so your issue is more like a feature request, unless there is something more, legacy c++ support and runtime size support. Now, `ca::array<>` owes it's speed to the size constraint being known at compile-time and legacy c++ would complicate maintaining for me, because c++20 makes for compact, easier-to-maintain code. Also, it makes it easier for the compiler to optimize the code (even though a runtime size (`N` variable) would not complicate things a lot, I believe). Still, I'd need an additional variable and the code was written to take-up as little memory as possible, 2 pointers and no more, as is usual for deques.

The reason why I wrote this container was performance. I had a command deque and it was very slow due to heap allocations and freeing. On my side, the maximum size of this command deque is known at compile-time and I put the code online to save the time of other people, if they needed the same functionality and I'd benefit from bug reports. So, unless there is more I can't really help.

Upon review, I fixed additional bugs, hopefully the code still works :)

**Comment by user706** [comment]
ok, thanks.


> I wrote this:
> 
> ```c++
> #include "array.hpp"
> 
> int main()
> {
>   constexpr size_t num_el = 3;
>   int arr[10];
>   ca::array<int, num_el, ca::USER>ca(arr);
> 
>   return 0;
> }
> ```

Not sufficient for my needs. I currently need it to have a size that is not known at compile time. The above will not work if `constexpr` is removed.

> I had a command deque and it was very slow due to heap allocations and freeing.

That's why I want to handle the dynamic memory, via gcc/clang variable length arrays (or `alloca`) on the stack instead. That way I can get around the heap; have runtime size and still be super-fast.

I've modified your code to compile under C++17. It now has a constructor, taking the desired size (at runtime). I have 2 extra const data members: `CAP` and `N` (they are const member variables). Then I've optimized a bit, by replacing instances such as `&a_[N - 1]` with `&a_[CAP]`.

I'll definitely keep both `CAP` and `N` as const member variables, because if I keep only one of them, I occasionally have to let the CPU compute things such as `N-1`, or `CAP+1`, which I don't want.

**Comment by user706** [comment]
Ahh... even faster ... is to have another const member variable, holding the address of the last array-position

```cpp
const T* const lastStorageAddress_ = &a_[N - 1];
```

and then replace instances of `&a_[N - 1]` with `lastStorageAddress_`

**Comment by user706** [comment]
> Upon review, I fixed additional bugs, hopefully the code still works :)

I hope so as well. I can now in fact uncomment more stuff for my C++17 version (well actuall... Debian buster, to be precise), that was not compiling previously (something about ambigous function resolution).

The conversion to C++17 was pretty straigthforward actually:

```cpp
// at the top
#define requires(...) /**/

// modify stuff like
//     constexpr auto next(auto const p) const noexcept
// to 
  template<typename Tx>
  constexpr auto next(Tx const p) const noexcept

// modify stuff like
//    template <int = 0>
//    constexpr iterator insert(const_iterator const i, auto&& v)
// to
  template <int = 0, typename Tx>
  constexpr iterator insert(const_iterator const i, Tx&& v)



// comment out some noexcepts such as
//     //noexcept(noexcept(insert<0>(i, std::move(v))))            // otherwise not compiling in debian buster


// comment out stuff like    [[unlikely]]


// etc.

// at the bottom
#undef requires

**Comment by user1095108** [comment]
I'm happy it works for you, consider switching to arch linux, which has the latest and greatest tools. To be honest, you can tweak debian as well to get those.

> Not sufficient for my needs. I currently need it to have a size that is not known at compile time. The above will not work if constexpr is removed.

To me, this is indicative that you are using a wrong kind of container. What you need is a dynamic container :), i.e. something that allocates at run-time :)

I could do just fine without ca::array<>, only it would not be as fast.

**Comment by user706** [comment]
> To me, this is indicative that you are using a wrong kind of container. What you need is a dynamic container :), i.e. something that allocates at run-time :)

But I cannot use `boost::circular_buffer<>`, since it uses the heap.

I want to use a stack-allocated buffer, such as you get via `alloca` or variable length arrays. (Why? Since it is super-fast and still **dynamic in it's setup size (during runtime), but fixed after that!**)

> I could do just fine without ca::array<>, only it would not be as fast.

That's why I've modified your code, to now suit my usecase. :)

**Comment by user1095108** [comment]
If you really, really wanted boost to use the stack, there's a way, if you provide it with a container using a stack allocator and you can find examples online. This is also why I made `push_front()` such as it is, if boost was the thing I wanted to use, I would have used it, but it was very bulky at the time and since I had complete freedom, even if it was just a few bytes and nanoseconds, I didn't want to write even slightly bulkier/slower code.

**Comment by user706** [comment]
Yes. 
But I definately do not want to pull in a stack allocator (succh as this great one https://howardhinnant.github.io/stack_alloc.html ) just to use boost, which has all kinds of dynamic stuff such as resizing the capacity, which I do not want; since my usecase is: size specified during runtime [setup], and then remains fixed

Plus boost is super-slow.
I did a benchmark:
* yours: 445530 micoseconds
* mine: 446530 micoseconds [size as const member ... etc.]
* boost: 715069 micoseconds

Here's the test-code for boost (as you can see, I just did very many push_back's)
```cpp
#include <iostream>

#include <boost/circular_buffer.hpp>
#include <chrono>

int main()
{
  const std::size_t numEl = 10;
  boost::circular_buffer<int> ca{numEl};

  auto start = std::chrono::steady_clock::now();
  for (int i = 0; i != 999999999; ++i) {
      ca.push_back(i);
  }
  auto end = std::chrono::steady_clock::now();
  std::chrono::microseconds duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
  std::cout << "took: " << duration.count() << " micoseconds" << std::endl;
}
```

**Comment by user706** [comment]
> stack allocator (succh as this great one https://howardhinnant.github.io/stack_alloc.html )

Well, actually that stack allocator also needs it's memory size at compile-time:
https://github.com/HowardHinnant/HowardHinnant.github.io/blob/0568bfe2e274721ef42a3a31cbc7f24367347e0b/short_alloc.h#L30

I don't know if there is really any alternative to variable length arrays or `alloca`...
edit: yip... https://stackoverflow.com/questions/4082532/is-there-an-allocator-that-uses-alloca-and-is-otherwise-c-stl-compliant

edit2:
Seems I'd need to write my own allocator... taking an constructor argument... a variable length array:

kindof modifying [this](https://howardhinnant.github.io/stack_alloc.html) to:

```cpp
int main()
{
   std::size_t mysize = 3;
   int varLenArrayBuf[mysize];

    // Create the stack-based arena from which to allocate
    SmallVector<int>::allocator_type::arena_type a(varLenArrayBuf);   // pass constructor argument
    // Create the vector which uses that arena.
    SmallVector<int> v{a};
    // Exercise the vector and note that new/delete are not getting called.
    v.push_back(1);
```

I'm not going to do that. I don't want the memory to change. I only want to set the size during runtime.

**Comment by user706** [comment]
hmmm... what is pretty strange and starteling, is the result I get from this comparison of variable length arrays and heap memory:

```cpp
#include <iostream>
#include <chrono>
#include <numeric>

template<typename T>
class HeapBuf
{
public:
    HeapBuf(std::size_t numEl) : buf_{new T[numEl]}, numEl_{numEl}
    {}
    ~HeapBuf() {
        delete[] buf_;
    }
    const T* cbegin() const {
        return buf_;
    }
    T* begin() const {
        return buf_;
    }
    const T* cend() const {
        return buf_ + numEl_;
    }
    T* end() const {
        return buf_ + numEl_;
    }

private:
    T* buf_;
    std::size_t numEl_;
};


int main()
{
    constexpr unsigned LIM = 200000;
    {
        unsigned sum{0};

        auto start = std::chrono::steady_clock::now();
        for (unsigned i = 1; i <= LIM; ++i) {
            unsigned arr[i];
            //std::iota(arr, arr+i, i);
            //sum += std::accumulate(arr, arr+i, unsigned(0));
            sum += std::uintptr_t( arr ); // sum address to prevent optimization
        }
        auto end = std::chrono::steady_clock::now();
        std::cout << sum << '\n';
        std::chrono::microseconds duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
        std::cout << "took: " << duration.count()/1000000. << " seconds" << std::endl;
    }
    std::cout << "=============================================================================\n";
    {
        unsigned sum{0};

        auto start = std::chrono::steady_clock::now();
        for (unsigned i = 1; i <= LIM; ++i) {
            HeapBuf<unsigned> hp(i);
            //std::iota(hp.begin(), hp.end(), i);;
            //sum += std::accumulate(hp.cbegin(), hp.cend(), unsigned(0));
            sum += std::uintptr_t( hp.cbegin() ); // sum address to prevent optimization
        }
        auto end = std::chrono::steady_clock::now();
        std::cout << sum << '\n';
        std::chrono::microseconds duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
        std::cout << "took: " << duration.count()/1000000. << " seconds" << std::endl;
    }
    
}
```

My result:
```python
1822732800
took: 0.12742 seconds     # variable length array takes longer
=============================================================================
330016912
took: 0.004433 seconds    # heap memory is quicker
```

But on wandbox it is the opposite: https://wandbox.org/permlink/nAmtD5YyOpEZlKF8

Strange.
In fact I did get faster times for varlen arrays on my laptop initially, but then all of a sudden the heap was faster and that's still the case.

Changing the code to have `constexpr unsigned LIM = 800000;`... I get this completely ridiculous result on my laptop:
```python
2567358464
took: 2.16914 seconds     # variable length array super ridiculously slow. Why????
=============================================================================
460098608
took: 0.017966 seconds
```

**Comment by user1095108** [comment]
Well, you've done exactly as I imagined users would, copy&pasted what you needed, so that's fine, your `ca::array<>` will be tailored to your needs.

I think changing capacity while the array is full could lead to problems, hopefully you've thought this out carefully. I still think you haven't thought things over, like you should :)

`return n < decltype(n){} ? N + n : n;`

could return different results, if `N` changes during runtime, if the array isn't empty. You need to clear the array when changing capacity.

**Comment by user1095108** [comment]
I am going to close this one as well, thanks for the issue, it was interesting. Surely you have solved everything yourself.
